algoritmo "Graus celsius em Farenheit"
// Função :Transformar graus celsius em graus farenheit
// Autor :Gabriel Pereira Dias
// Data : 13/04/2026
var
   C: real
   F: real

inicio
      escreva ("Digite a temperatura em graus celsius: ")
      leia (C)
      F <- (9 * C/5) + 32
      escreva ("A temperatura ", C ,"° celsius é equivalente à", F ,"° Farenheit")
// Seção de Comandos 
fimalgoritmo
